services:
  react:
    container_name: frontend
    build:
      context: .
      target: react
    restart: always
    ports:
      - 3008:3000
      - 3009:3001
    links:
      - api
    networks:
      static-network:
       ipv4_address: 172.28.0.2

  api:
    container_name: api
    build:
      context: .
      target: api
    restart: always
    ports:
      - 8080:8080
    links:
      - db
    networks:
      static-network:
       ipv4_address: 172.28.0.3

  db:
    container_name: database
    build:
      context: .
      target: db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: games-reviews
    networks:
      static-network:
       ipv4_address: 172.28.0.4

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24