services:
  react:
    container_name: frontend
    build:
      context: .
      target: react
    restart: always
    ports:
      - "3008:3000"
      - "3009:3001"
    links:
      - "db:database"
    #volumes:
    #   - ./.:/usr/src/app/game-review-ynov

  db:
    container_name: database
    build:
      context: .
      target: db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: games-reviews
