ALTER TABLE games DROP FOREIGN KEY games_ibfk_1;
ALTER TABLE games DROP FOREIGN KEY games_ibfk_2;

ALTER TABLE reviews DROP FOREIGN KEY reviews_ibfk_1;
ALTER TABLE reviews DROP FOREIGN KEY reviews_ibfk_2;

DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Platforms;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Games;
DROP TABLE IF EXISTS Reviews;

DROP DATABASE IF EXISTS GameReviews;